// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoEnfermeriaMVC.Data;

#nullable disable

namespace ProyectoEnfermeriaMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ProyectoEnfermeriaMVC.Models.Testimonio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Testimonios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mensaje = "Gracias a la información pude cuidar mejor a mi bebé.",
                            Nombre = "María"
                        },
                        new
                        {
                            Id = 2,
                            Mensaje = "El método canguro nos ayudó muchísimo con nuestro hijo prematuro.",
                            Nombre = "Carlos"
                        },
                        new
                        {
                            Id = 3,
                            Mensaje = "Una guía práctica y sencilla que me dio confianza en la lactancia.",
                            Nombre = "Laura"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
